# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) 2026 Nethermind
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.


{ stdenv
, lib
, dpkg
, buildNpmPackage
, makeWrapper
, nodejs_20
, python3
, pkg-config
, sqlite
, sgxDebianRepo
}:

buildNpmPackage rec {
  pname = "sgx-dcap-pccs";
  version = "1.23.100.0";

  # Extract PCCS source from Intel's Debian package
  src = stdenv.mkDerivation {
    name = "sgx-dcap-pccs-source-${version}";
    src = sgxDebianRepo;
    
    nativeBuildInputs = [ dpkg ];
    
    unpackPhase = ''
      tar -xzf $src
      dpkg-deb -x sgx_debian_local_repo/pool/main/s/sgx-dcap-pccs/sgx-dcap-pccs_${version}-noble1_amd64.deb unpacked
    '';
    
    installPhase = ''
      mkdir -p $out
      cp -r unpacked/opt/intel/sgx-dcap-pccs/* $out/
    '';
  };

  # Patch to allow external log directory
  patches = [
    ./external-logs.patch
  ];

  # Copy the pre-generated package-lock.json into the source
  postPatch = ''
    cp ${./package-lock.json} package-lock.json
  '';

  # Hash of npm dependencies fetched from the npm registry
  # Generated by running: nix build .#sgx-dcap-pccs
  npmDepsHash = "sha256-/gz8NAYtJKc56SufR+HMbhNuotJtXfUlr7/ldYSC1Ho=";

  nativeBuildInputs = [
    python3          # Required for node-gyp to build native modules
    pkg-config       # Helps find system libraries
    nodejs_20
    makeWrapper      # For creating the bin wrapper
  ];

  buildInputs = [
    sqlite           # Required by sqlite3 npm module
  ];

  # sqlite3 native module needs writable cache during build
  makeCacheWritable = true;
  
  # PCCS is a server app with no build step
  dontNpmBuild = true;

  # Create wrapper script pointing to correct installation path
  # buildNpmPackage installs to $out/lib/node_modules/<name from package.json>
  # For PCCS, package.json has "name": "PCCS" (uppercase)
  # Note: We don't use --chdir here because systemd's WorkingDirectory should control
  # where PCCS runs from (/var/lib/sgx-dcap-pccs), not the Nix store.
  # Node.js will find modules via NODE_PATH environment variable set by the systemd service.
  postInstall = ''
    mkdir -p $out/bin
    makeWrapper ${nodejs_20}/bin/node $out/bin/pccs \
      --add-flags "$out/lib/node_modules/PCCS/pccs_server.js"
  '';

  meta = with lib; {
    description = "Intel SGX DCAP Provisioning Certificate Caching Service";
    longDescription = ''
      PCCS is a lightweight caching proxy for Intel's Provisioning Certificate Service.
      It retrieves PCK certificates and other attestation collaterals on-demand and
      caches them locally in a SQLite or MySQL database.
      
      This service is required for SGX/TDX attestation to work properly, as it provides
      the platform certificates needed for quote verification.
      
      This package includes pre-built node_modules with native modules compiled for NixOS.
    '';
    homepage = "https://github.com/intel/SGXDataCenterAttestationPrimitives";
    license = licenses.bsd3;
    platforms = platforms.linux;
    mainProgram = "pccs";
  };
}
