# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) 2026 Nethermind
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.


# All Intel SGX/TDX packages consolidated in one file
# Uses the mkSgxPackage builder to reduce duplication
{ callPackage, lib, stdenv, dpkg, buildNpmPackage, nodejs_20, python3, pkg-config, sqlite
, protobuf, openssl, curl, zlib, systemd, boost183, makeWrapper, jansson }:

let
  # Base repo with all .deb files pre-unpacked
  sgxDebianRepo = callPackage ./sgx-debian-local-repo.nix { };
  
  # Generic builder for standard SGX packages
  mkSgxPackage = callPackage ./builder.nix { inherit sgxDebianRepo makeWrapper; };

in rec {
  # Export the base repo (needed by special packages like sgx-enclaves)
  inherit sgxDebianRepo;
  
  # === Core SGX Libraries ===
  
  libsgx-enclave-common = mkSgxPackage {
    pname = "libsgx-enclave-common";
    version = "2.26.100.0";
    debPath = "pool/main/libs/libsgx-enclave-common";
    buildInputs = [ protobuf ];
  };
  
  libsgx-urts = mkSgxPackage {
    pname = "libsgx-urts";
    version = "2.26.100.0";
    debPath = "pool/main/libs/libsgx-urts";
    buildInputs = [ protobuf libsgx-enclave-common ];
  };
  
  # === DCAP Quote Generation Libraries ===
  
  libsgx-qe3-logic = mkSgxPackage {
    pname = "libsgx-qe3-logic";
    version = "1.23.100.0";
    debPath = "pool/main/libs/libsgx-qe3-logic";
    buildInputs = [ openssl libsgx-urts sgx-enclaves ];
    
    installPhase = ''
      runHook preInstall
      
      mkdir -p $out/lib
      cp -r ${sgxDebianRepo}/sgx_debian_local_repo/pool/main/libs/libsgx-qe3-logic/unpacked/usr/lib/x86_64-linux-gnu/* $out/lib/
      
      # CRITICAL: Symlink Intel-signed QE3 enclave into lib directory
      # The libsgx_qe3_logic.so library expects to find the signed enclave in the same directory
      ln -s ${sgx-enclaves}/lib/libsgx_qe3.signed.so $out/lib/
      ln -s ${sgx-enclaves}/lib/libsgx_qe3.signed.so.1 $out/lib/
      
      runHook postInstall
    '';
  };
  
  libsgx-pce-logic = mkSgxPackage {
    pname = "libsgx-pce-logic";
    version = "1.23.100.0";
    debPath = "pool/main/libs/libsgx-pce-logic";
    buildInputs = [ openssl libsgx-urts sgx-enclaves ];
    
    installPhase = ''
      runHook preInstall
      
      mkdir -p $out/lib
      cp -r ${sgxDebianRepo}/sgx_debian_local_repo/pool/main/libs/libsgx-pce-logic/unpacked/usr/lib/x86_64-linux-gnu/* $out/lib/
      
      # CRITICAL: Symlink Intel-signed PCE enclave into lib directory
      # The libsgx_pce_logic.so library expects to find the signed enclave in the same directory
      ln -s ${sgx-enclaves}/lib/libsgx_pce.signed.so $out/lib/
      ln -s ${sgx-enclaves}/lib/libsgx_pce.signed.so.1 $out/lib/
      
      runHook postInstall
    '';
  };
  
  libsgx-tdx-logic = mkSgxPackage {
    pname = "libsgx-tdx-logic";
    version = "1.23.100.0";
    debPath = "pool/main/libs/libsgx-tdx-logic";
    buildInputs = [ openssl protobuf curl libsgx-urts libsgx-pce-logic sgx-enclaves ];
    
    installPhase = ''
      runHook preInstall
      
      mkdir -p $out/lib
      cp -r ${sgxDebianRepo}/sgx_debian_local_repo/pool/main/libs/libsgx-tdx-logic/unpacked/usr/lib/x86_64-linux-gnu/* $out/lib/
      
      # CRITICAL: Symlink Intel-signed enclaves into lib directory
      # The libsgx_tdx_logic.so library expects to find the signed enclaves in the same directory
      ln -s ${sgx-enclaves}/lib/libsgx_tdqe.signed.so.1 $out/lib/
      ln -s ${sgx-enclaves}/lib/libsgx_id_enclave.signed.so.1 $out/lib/
      ln -s ${sgx-enclaves}/lib/libsgx_qe3.signed.so.1 $out/lib/
      ln -s ${sgx-enclaves}/lib/libsgx_qve.signed.so.1 $out/lib/
      
      runHook postInstall
    '';
  };
  
  libsgx-dcap-ql = mkSgxPackage {
    pname = "libsgx-dcap-ql";
    version = "1.23.100.0";
    debPath = "pool/main/libs/libsgx-dcap-ql";
    buildInputs = [ openssl protobuf curl zlib libsgx-qe3-logic libsgx-pce-logic ];
  };
  
  libsgx-dcap-default-qpl = mkSgxPackage {
    pname = "libsgx-dcap-default-qpl";
    version = "1.23.100.0";
    debPath = "pool/main/libs/libsgx-dcap-default-qpl";
    buildInputs = [ openssl curl jansson zlib ];
    # Note: Config file is generated by systemd service, not copied from package
  };
  
  # === MPA Registration Libraries ===
  
  libsgx-ra-uefi = mkSgxPackage {
    pname = "libsgx-ra-uefi";
    version = "1.23.100.0";
    debPath = "pool/main/libs/libsgx-ra-uefi";
    buildInputs = [ curl ];
  };
  
  libsgx-ra-network = mkSgxPackage {
    pname = "libsgx-ra-network";
    version = "1.23.100.0";
    debPath = "pool/main/libs/libsgx-ra-network";
    buildInputs = [ curl ];
  };
  
  # === Intel-Signed Enclaves (Special handling required) ===
  
  sgx-enclaves = stdenv.mkDerivation rec {
    pname = "sgx-enclaves";
    version = "1.23.100.0";
    pceVersion = "2.26.100.0";
    
    # CRITICAL: Do not modify Intel-signed enclaves
    # Changing MRENCLAVE hash would break remote attestation
    dontUnpack = true;
    dontPatchELF = true;
    dontStrip = true;
    dontAutoPatchelf = true;
    
    installPhase = ''
      runHook preInstall
      
      mkdir -p $out/lib
      
      # Copy all signed enclaves from pre-unpacked locations
      cp ${sgxDebianRepo}/sgx_debian_local_repo/pool/main/libs/libsgx-ae-tdqe/unpacked/usr/lib/x86_64-linux-gnu/*.signed.so* $out/lib/ || true
      cp ${sgxDebianRepo}/sgx_debian_local_repo/pool/main/libs/libsgx-ae-qe3/unpacked/usr/lib/x86_64-linux-gnu/*.signed.so* $out/lib/ || true
      cp ${sgxDebianRepo}/sgx_debian_local_repo/pool/main/libs/libsgx-ae-qve/unpacked/usr/lib/x86_64-linux-gnu/*.signed.so* $out/lib/ || true
      cp ${sgxDebianRepo}/sgx_debian_local_repo/pool/main/libs/libsgx-ae-id-enclave/unpacked/usr/lib/x86_64-linux-gnu/*.signed.so* $out/lib/ || true
      cp ${sgxDebianRepo}/sgx_debian_local_repo/pool/main/s/sgx-aesm-service/unpacked/usr/lib/x86_64-linux-gnu/*.signed.so* $out/lib/ || true
      
      runHook postInstall
    '';
    
    meta = with lib; {
      description = "Intel-signed SGX/TDX enclaves (TDQE, QE3, QVE, ID, PCE)";
      homepage = "https://github.com/intel/SGXDataCenterAttestationPrimitives";
      license = licenses.unfree;  # Intel-signed binaries
      platforms = platforms.linux;
    };
  };
  
  # === TDX Quote Generation Service ===
  
  tdx-qgs = let debPath = "pool/main/t/tdx-qgs"; in mkSgxPackage {
    pname = "tdx-qgs";
    version = "1.23.100.0";
    inherit debPath;
    buildInputs = [
      openssl protobuf curl zlib systemd boost183
      libsgx-dcap-ql libsgx-dcap-default-qpl libsgx-tdx-logic sgx-enclaves
    ];
    
    installPhase = ''
      runHook preInstall
      
      mkdir -p $out/bin $out/lib $out/etc
      
      # Copy qgs binary from /opt/intel/tdx-qgs/
      cp ${sgxDebianRepo}/sgx_debian_local_repo/${debPath}/unpacked/opt/intel/tdx-qgs/qgs $out/bin/
      
      # Copy configuration if present
      if [ -f ${sgxDebianRepo}/sgx_debian_local_repo/${debPath}/unpacked/etc/qgs.conf ]; then
        cp ${sgxDebianRepo}/sgx_debian_local_repo/${debPath}/unpacked/etc/qgs.conf $out/etc/
      fi
      
      # Copy any libraries
      if [ -d ${sgxDebianRepo}/sgx_debian_local_repo/${debPath}/unpacked/usr/lib/x86_64-linux-gnu ]; then
        cp -r ${sgxDebianRepo}/sgx_debian_local_repo/${debPath}/unpacked/usr/lib/x86_64-linux-gnu/* $out/lib/ || true
      fi
      
      # Wrap qgs with proper library paths
      wrapProgram $out/bin/qgs \
        --prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath [
          libsgx-dcap-ql libsgx-dcap-default-qpl libsgx-tdx-logic sgx-enclaves
          openssl protobuf curl zlib systemd boost183 stdenv.cc.cc.lib
        ]}:$out/lib
      
      runHook postInstall
    '';
    
    meta.mainProgram = "qgs";
  };
  
  # === TDX QGS Daemon (Wrapper package) ===
  
  tdx-qgs-daemon = stdenv.mkDerivation {
    pname = "tdx-qgs-daemon";
    version = tdx-qgs.version;
    
    dontUnpack = true;
    nativeBuildInputs = [ makeWrapper ];
    buildInputs = [ tdx-qgs sgx-enclaves ];
    
    installPhase = ''
      runHook preInstall
      
      mkdir -p $out/{bin,etc,share/doc/tdx-qgs}
      
      # Link to the QGS binary (already wrapped with proper library paths)
      ln -s ${tdx-qgs}/bin/qgs $out/bin/qgs
      
      # Install default QGS configuration
      cat > $out/etc/qgs.conf <<'EOF'
# TDX Quote Generation Service Configuration
vsock_port=4050
log_level=info
log_file=/var/log/qgs/qgs.log
max_connections=100
timeout_seconds=30
EOF
      
      # Install default QPL configuration
      cat > $out/etc/sgx_default_qcnl.conf <<'EOF'
# Intel SGX DCAP Quote Provider Library Configuration
PCCS_URL=https://api.trustedservices.intel.com/sgx/certification/v4/
USE_SECURE_CERT=TRUE
RETRY_TIMES=6
RETRY_DELAY=10
PCK_CACHE_EXPIRE_HOURS=168
EOF
      
      runHook postInstall
    '';
    
    meta = with lib; {
      description = "Intel TDX Quote Generation Service for remote attestation";
      homepage = "https://github.com/intel/SGXDataCenterAttestationPrimitives";
      license = licenses.bsd3;
      platforms = [ "x86_64-linux" ];
      mainProgram = "qgs";
    };
  };
  
  # === MPA Registration Service ===
  
  sgx-ra-service = let debPath = "pool/main/s/sgx-ra-service"; in mkSgxPackage {
    pname = "sgx-ra-service";
    version = "1.23.100.0";
    inherit debPath;
    buildInputs = [ curl libsgx-ra-uefi libsgx-ra-network ];
    
    installPhase = ''
      runHook preInstall
      
      mkdir -p $out/bin $out/etc $out/share/systemd/system
      
      # Copy binaries from /opt/intel/sgx-ra-service/
      cp ${sgxDebianRepo}/sgx_debian_local_repo/${debPath}/unpacked/opt/intel/sgx-ra-service/mpa_manage $out/bin/
      cp ${sgxDebianRepo}/sgx_debian_local_repo/${debPath}/unpacked/opt/intel/sgx-ra-service/mpa_registration $out/bin/
      
      # Copy configuration template
      if [ -f ${sgxDebianRepo}/sgx_debian_local_repo/${debPath}/unpacked/etc/mpa_registration.conf ]; then
        cp ${sgxDebianRepo}/sgx_debian_local_repo/${debPath}/unpacked/etc/mpa_registration.conf $out/etc/
      fi
      
      # Copy systemd service file
      if [ -f ${sgxDebianRepo}/sgx_debian_local_repo/${debPath}/unpacked/lib/systemd/system/mpa_registration_tool.service ]; then
        cp ${sgxDebianRepo}/sgx_debian_local_repo/${debPath}/unpacked/lib/systemd/system/mpa_registration_tool.service $out/share/systemd/system/
      fi
      
      # Wrap binaries with proper library paths
      for bin in mpa_manage mpa_registration; do
        wrapProgram $out/bin/$bin \
          --prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath [
            libsgx-ra-uefi libsgx-ra-network curl stdenv.cc.cc.lib
          ]}
      done
      
      runHook postInstall
    '';
    
    meta.mainProgram = "mpa_manage";
  };
  
  # === PCK ID Retrieval Tool ===
  
  sgx-pck-id-retrieval-tool = let debPath = "pool/main/s/sgx-pck-id-retrieval-tool"; in mkSgxPackage {
    pname = "sgx-pck-id-retrieval-tool";
    version = "1.23.100.0";
    inherit debPath;
    buildInputs = [ curl openssl zlib libsgx-urts libsgx-ra-uefi sgx-enclaves ];
    
    installPhase = ''
      runHook preInstall
      
      mkdir -p $out/bin $out/etc/sgx-pck-id-retrieval-tool $out/share/doc/sgx-pck-id-retrieval-tool
      
      # Copy main binary
      cp ${sgxDebianRepo}/sgx_debian_local_repo/${debPath}/unpacked/opt/intel/sgx-pck-id-retrieval-tool/PCKIDRetrievalTool $out/bin/
      
      # Copy configuration template
      cp ${sgxDebianRepo}/sgx_debian_local_repo/${debPath}/unpacked/opt/intel/sgx-pck-id-retrieval-tool/network_setting.conf $out/etc/sgx-pck-id-retrieval-tool/ || true
      
      # Copy documentation
      cp ${sgxDebianRepo}/sgx_debian_local_repo/${debPath}/unpacked/opt/intel/sgx-pck-id-retrieval-tool/README.txt $out/share/doc/sgx-pck-id-retrieval-tool/ || true
      cp ${sgxDebianRepo}/sgx_debian_local_repo/${debPath}/unpacked/opt/intel/sgx-pck-id-retrieval-tool/License.txt $out/share/doc/sgx-pck-id-retrieval-tool/ || true
      
      # CRITICAL: Symlink Intel-signed enclaves into bin directory
      # The PCKIDRetrievalTool expects to find these enclaves in the same directory as the binary
      ln -s ${sgx-enclaves}/lib/libsgx_pce.signed.so.1 $out/bin/
      ln -s ${sgx-enclaves}/lib/libsgx_id_enclave.signed.so.1 $out/bin/
      
      # Wrap binary with proper library paths
      wrapProgram $out/bin/PCKIDRetrievalTool \
        --prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath [
          libsgx-urts libsgx-ra-uefi sgx-enclaves curl openssl zlib stdenv.cc.cc.lib
        ]}
      
      runHook postInstall
    '';
    
    meta = {
      description = "Intel SGX PCK Certificate ID Retrieval Tool";
      mainProgram = "PCKIDRetrievalTool";
    };
  };
  
  # === PCCS (Special Node.js package) ===
  
  sgx-dcap-pccs = buildNpmPackage rec {
    pname = "sgx-dcap-pccs";
    version = "1.23.100.0";
    
    # Extract PCCS source from Intel's Debian package
    src = stdenv.mkDerivation {
      name = "sgx-dcap-pccs-source-${version}";
      dontUnpack = true;
      
      installPhase = ''
        mkdir -p $out
        cp -r ${sgxDebianRepo}/sgx_debian_local_repo/pool/main/s/sgx-dcap-pccs/unpacked/opt/intel/sgx-dcap-pccs/* $out/
      '';
    };
    
    # Patch to allow external log directory
    patches = [
      ./sgx-dcap-pccs/external-logs.patch
    ];
    
    # Copy the pre-generated package-lock.json
    postPatch = ''
      cp ${./sgx-dcap-pccs/package-lock.json} package-lock.json
    '';
    
    npmDepsHash = "sha256-/gz8NAYtJKc56SufR+HMbhNuotJtXfUlr7/ldYSC1Ho=";
    
    nativeBuildInputs = [ python3 pkg-config nodejs_20 makeWrapper ];
    buildInputs = [ sqlite ];
    
    makeCacheWritable = true;
    dontNpmBuild = true;
    
    postInstall = ''
      mkdir -p $out/bin
      makeWrapper ${nodejs_20}/bin/node $out/bin/pccs \
        --add-flags "$out/lib/node_modules/PCCS/pccs_server.js"
    '';
    
    meta = with lib; {
      description = "Intel SGX DCAP Provisioning Certificate Caching Service";
      homepage = "https://github.com/intel/SGXDataCenterAttestationPrimitives";
      license = licenses.bsd3;
      platforms = platforms.linux;
      mainProgram = "pccs";
    };
  };
}
